/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 buildings.gltf 
Author: OndyRen (https://sketchfab.com/saurondra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-inspired-low-poly-buildings-db883b9fd31f438e94abd3cb8cb3ead5
Title: Star Wars inspired low poly buildings
*/

import { useGLTF } from '@react-three/drei'

export function Buildings(props) {
  const { nodes, materials } = useGLTF('/models/buildings/buildings.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.building} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/buildings/buildings.gltf')
